repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.3.1
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
    -   id: isort # sort imports alphabetically and separates import into sections
        args: [-w=88, -m=3, -tc, -sp=setup.cfg ]